### ISSUE TITLE
production setup docu - TODO

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#702]
- [ ] we need python3 - `mkvirtualenv` does not default to it on older systems
- [ ] siteid etc? example multisite?
- [ ] database docu (just link to django config docu?)
- [ ] sentry integration?
- [ ] small cleanups
- [ ] email setup (again django docu?)
- [ ] django-admin settings (site etc.)
- [ ] "how to get started" (first organisation etc.)

**Comment by rmader** [comment]
```
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='127.0.0.1'
```

**Comment by rmader** [comment]
mkvirtualenv --python=/usr/bin/python3 aplus

curl
gettext
nodejs 12...

sample db setup:
apt-get install postgresql-11
su postgres
createuser aplus
createdb aplus
psql
grant ALL on DATABASE aplus TO aplus;

local.py:
create folder!
exchange allowed urls
SITE_ID=1
